FROM node:18.16.0

WORKDIR /frontend

COPY package*.json ./

RUN npm install --silent
RUN chown -R node /frontend/node_modules
#RUN chown -R 777 ./node_modules/.cache/.eslintcache
# RUN cd node_modules/.cache && chmod -R 777 node_modules/.cache
#RUN sudo npm install -g eslint --unsafe-perm=true --allow-root
RUN npm install -g react-scripts --silent

COPY . .

EXPOSE 80
