version: '3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    environment: 
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "80:80"
    volumes:
      - ./frontend:/frontend

  ganache:
    container_name: ganache
    image: trufflesuite/ganache
    ports:
      - 8545:8545
    volumes:
      - ganache_data:/ganache_data
    depends_on:
      - truffle
    
  truffle:
    container_name: truffle
    build: ./truffle
    volumes:
      - .:/truffle

volumes:
  ganache_data:       

